// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Case struct {
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	Author    *string    `json:"author"`
	CreatedAt *time.Time `json:"createdAt"`
	UpdateAt  *time.Time `json:"updateAt"`
}

type NewCase struct {
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	Author    *string    `json:"author"`
	CreatedAt *time.Time `json:"createdAt"`
	UpdateAt  *time.Time `json:"updateAt"`
}

type NewUsecase struct {
	ID        string     `json:"id"`
	Title     string     `json:"title"`
	Author    string     `json:"author"`
	Content   *string    `json:"content"`
	Tags      *string    `json:"tags"`
	Completed *bool      `json:"completed"`
	CreatedAt *time.Time `json:"createdAt"`
	UpdateAt  *time.Time `json:"updateAt"`
}

type NewUser struct {
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	Email     *string    `json:"email"`
	CreatedAt *time.Time `json:"createdAt"`
}

type Usecase struct {
	ID        string     `json:"id"`
	Title     string     `json:"title"`
	Author    string     `json:"author"`
	Content   *string    `json:"content"`
	Tags      []*string  `json:"tags"`
	Completed *bool      `json:"completed"`
	CreatedAt *time.Time `json:"createdAt"`
	UpdateAt  *time.Time `json:"updateAt"`
	Cases     []*Case    `json:"cases"`
}

type User struct {
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	Email     *string    `json:"email"`
	Cases     []*Case    `json:"cases"`
	Usecase   []*Usecase `json:"usecase"`
	CreatedAt *time.Time `json:"createdAt"`
}
